version: 2

models:
  - name: commits
    description: "Commits"
    meta:
      gooddata:
        model_id: github
    columns:
      - name: commit_id
        description: "Commit ID"
        data_type: "INT"
        tests:
          - dbt_constraints.primary_key
        meta:
          gooddata:
            ldm_type: primary_key
      - name: user_id
        data_type: "INT"
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('users')
              pk_column_name: user_id
        meta:
          gooddata:
            ldm_type: reference
            referenced_table: users
            # TODO is this needed? We do not support multi-column grains/references yet
            # referenced_column_name: user_id
      - name: repo_id
        data_type: "INT"
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('repos')
              pk_column_name: repo_id
        meta:
          gooddata:
            ldm_type: reference
            referenced_table: repos
            # TODO is this needed? We do not support multi-column grains/references yet
            # referenced_column_name: repo_id
      - name: commit_url
        data_type: "STRING"
        description: "Commit URL"
        meta:
          gooddata:
            ldm_type: label
            label_type: HYPERLINK
            attribute_column: commit_id
      - name: commit_title
        data_type: "STRING"
        description: "Commit title"
        meta:
          gooddata:
            ldm_type: attribute
      - name: created_at
        data_type: "TIMESTAMP"
        description: "Created at"
        meta:
          gooddata:
            ldm_type: date
