version: 2

models:
  - name: carriers
    meta:
      gooddata:
        model_id: faa
    columns:
      - name: code
        tests:
          - dbt_constraints.primary_key
        meta:
          gooddata:
            ldm_type: primary_key
      - name: name
      - name: nickname
