ARG PYTHON_VERSION=3.10
ARG DBT_VERSION=1.4.1
ARG DBT_IMAGE=ghcr.io/dbt-labs/dbt-core:$DBT_VERSION
FROM python:${PYTHON_VERSION}-slim-bullseye as builder

WORKDIR /dbt-gooddata

COPY ./src/dbt-gooddata .
RUN python3 setup.py sdist

ARG DBT_VERSION=1.4.1
ARG DBT_IMAGE=ghcr.io/dbt-labs/dbt-core:$DBT_VERSION
FROM $DBT_IMAGE

WORKDIR /usr/app

COPY src/requirements-dbt.txt requirements-dbt.txt
RUN pip3 install -r requirements-dbt.txt

ENV DBT_GOODATA_VERSION="0.1"
COPY --from=builder /dbt-gooddata/dist/dbt-gooddata-${DBT_GOODATA_VERSION}.tar.gz /artefacts/dbt-gooddata-${DBT_GOODATA_VERSION}.tar.gz
RUN pip3 install /artefacts/dbt-gooddata-${DBT_GOODATA_VERSION}.tar.gz

COPY src/packages.yml packages.yml
COPY src/dbt_project.yml dbt_project.yml
COPY src/models models
COPY src/macros macros
COPY src/profile/profiles.yml /root/.dbt/profiles.yml
RUN dbt deps

COPY src/gooddata_layouts gooddata_layouts
COPY src/gooddata.yml gooddata.yml

ENTRYPOINT ["dbt"]
