ARG PYTHON_VERSION=3.10
ARG DBT_VERSION=1.4.1
ARG DBT_IMAGE=ghcr.io/dbt-labs/dbt-core:$DBT_VERSION
ARG SRC_DATA_PIPELINE=data_pipeline
FROM python:${PYTHON_VERSION}-slim-bullseye as builder

ARG SRC_DATA_PIPELINE
WORKDIR /dbt-gooddata

COPY ./${SRC_DATA_PIPELINE}/dbt-gooddata .
RUN python3 setup.py sdist

ARG DBT_VERSION=1.4.1
ARG DBT_IMAGE=ghcr.io/dbt-labs/dbt-core:$DBT_VERSION
FROM $DBT_IMAGE

ARG SRC_DATA_PIPELINE
WORKDIR /usr/app

COPY ${SRC_DATA_PIPELINE}/requirements-dbt.txt requirements-dbt.txt
RUN pip3 install -r requirements-dbt.txt

ENV DBT_GOODATA_VERSION="0.1"
COPY --from=builder /dbt-gooddata/dist/dbt-gooddata-${DBT_GOODATA_VERSION}.tar.gz /artefacts/dbt-gooddata-${DBT_GOODATA_VERSION}.tar.gz
RUN pip3 install /artefacts/dbt-gooddata-${DBT_GOODATA_VERSION}.tar.gz

COPY ${SRC_DATA_PIPELINE}/packages.yml packages.yml
COPY ${SRC_DATA_PIPELINE}/dbt_project.yml dbt_project.yml
COPY ${SRC_DATA_PIPELINE}/models models
COPY ${SRC_DATA_PIPELINE}/macros macros
COPY ${SRC_DATA_PIPELINE}/profile/profiles.yml /root/.dbt/profiles.yml
RUN dbt deps

COPY ${SRC_DATA_PIPELINE}/gooddata_layouts gooddata_layouts
COPY ${SRC_DATA_PIPELINE}/gooddata.yml gooddata.yml

ENTRYPOINT ["dbt"]
