.docker:
  extends:
    - .base
  image: docker:stable
  tags:
    - docker
  services:
    - name: docker:20.10.12-dind
      alias: docker
  variables:
    DOCKER_HOST: 'tcp://docker:2376'
    DOCKER_DRIVER: 'overlay2'
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_TLS_VERIFY: '1'
    DOCKER_CERT_PATH: '/certs/client'
    DOCKER_BUILDKIT: '1'
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
