version: 2

models:
  - name: fact_sales
    description: "Sales"
    meta:
      gooddata:
        model_id: mark43
    columns:
      - name: SalesID
        description: "Sales ID"
        data_tests:
          - unique
          - not_null
          - dbt_constraints.primary_key:
              severity: ERROR
        meta:
          gooddata:
            ldm_type: primary_key

      - name: CustomerID
        description: "Customer ID"
        data_tests:
          - not_null
          - dbt_constraints.foreign_key:
              pk_table_name: ref('dim_customer')
              pk_column_name: CustomerID
        meta:
          gooddata:
            ldm_type: reference
            referenced_table: dim_customer

      - name: ProductID
        description: "Product ID"
        data_tests:
          - not_null
          - dbt_constraints.foreign_key:
              pk_table_name: ref('dim_product')
              pk_column_name: ProductID
        meta:
          gooddata:
            ldm_type: reference
            referenced_table: dim_product

      - name: TransactionDate
        description: "Date"

      - name: Quantity
        description: "Quantity"
        meta:
          gooddata:
            id: sales.quantity

      - name: SalesAmount
        description: "Amount"

      - name: Discount
        description: "Discount"

      - name: SalesChannel
        description: "Channel"
        data_tests:
          - accepted_values:
              values: ['Online', 'In-store']
