version: 2

models:
  - name: census
    meta:
      gooddata:
        model_id: data_science
    columns:
      - name: timestamp
      - name: continent
      - name: population
        description: Population of the continent
        meta:
          gooddata:
            id: census.population
